// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vVSRDZJvocQ4ts0DWZGxJ8RQocw7lo8',
    appId: '1:760460504305:web:b0e6b96a6601d2bb3a0d50',
    messagingSenderId: '760460504305',
    projectId: 'fir-app-f53b0',
    authDomain: 'fir-app-f53b0.firebaseapp.com',
    storageBucket: 'fir-app-f53b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQEro0WTAarAJfCmYxlEMZKNDV7G7Bdw',
    appId: '1:760460504305:android:cba836c16d5b138f3a0d50',
    messagingSenderId: '760460504305',
    projectId: 'fir-app-f53b0',
    storageBucket: 'fir-app-f53b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzOn6qJ4pibd3WRp9mrvV5i45qrJoN9E',
    appId: '1:760460504305:ios:781e9a4677822e993a0d50',
    messagingSenderId: '760460504305',
    projectId: 'fir-app-f53b0',
    storageBucket: 'fir-app-f53b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzOn6qJ4pibd3WRp9mrvV5i45qrJoN9E',
    appId: '1:760460504305:ios:781e9a4677822e993a0d50',
    messagingSenderId: '760460504305',
    projectId: 'fir-app-f53b0',
    storageBucket: 'fir-app-f53b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9vVSRDZJvocQ4ts0DWZGxJ8RQocw7lo8',
    appId: '1:760460504305:web:92d8b343b431e9de3a0d50',
    messagingSenderId: '760460504305',
    projectId: 'fir-app-f53b0',
    authDomain: 'fir-app-f53b0.firebaseapp.com',
    storageBucket: 'fir-app-f53b0.firebasestorage.app',
  );
}
